import React from 'react';
// import { useState, useEffect } from 'react'
import Head from 'next/head';
import Router from 'next/router';
// import Link from 'next/link';
// import axios from 'axios';
// import servicePath from '../../config/apiUrl';

import styles from './Header.module.css';
// import './header.css';

import { Row, Col, Menu, Icon } from 'antd';

const HeaderDes = () => {
/* 
  const [navArray, setNavArray] = useState([]);
  useEffect(() => {
    const getTypeUrl = servicePath.getTypeInfo;
    const fetchData = async () => {
      const result = await axios(getTypeUrl)
        .then((res) => {
          console.log(res.data);
          setNavArray(res.data.data);
          return res.data.data;
        })
      setNavArray(result)
    }
    fetchData();
  }, []);
  //首页标签节点s
  const navArrayNodes = navArray.map((item) => {
    return (
      <Menu.Item key={item.id}>
        <Icon type={item.icon} />
        {item.typeName}
      </Menu.Item>
    )
  })
  //跳转到列表页
   */
  const handleClick = (e) => {
    if (e.key == 0) {
      Router.push('/index')
    } else {
      Router.push('/list?id=' + e.key)
    }
  }

  return (
    <div
      // className="header"
      className={styles.header}
    >
      <Row justify="space-around" wrap="false"
        className={styles.main_header}>
        <Col xs={24} sm={24} md={24} lg={24} xl={24} span={24}>
          <Menu
            id="main-header-menu"
            mode="horizontal"
            onClick={handleClick}
          >
            <Menu.Item key="header-logo">
              <Icon type="home" />
              <span className="header-logo" id="header-logo">University</span>
            </Menu.Item>
            <Menu.Item key="header-first">
              <Icon type="home" />
              <span className="header-txt" id="header-first">首页</span>
            </Menu.Item>
            <Menu.Item key="header-selection">
              <Icon type="home" />
              <span className="header-txt" id="header-selection">精选好文</span>
            </Menu.Item>
            <Menu.Item key="header-search">
              <Icon type="home" />
              <span className="header-txt" id="header-search">Search</span>
            </Menu.Item>
            <Menu.Item key="header-write">
              <Icon type="home" />
              <span className="header-txt" id="header-write">写文章</span>
            </Menu.Item>
            <Menu.Item key="header-me">
              <Icon type="home" />
              <span className="header-txt" id="header-me">个人中心</span>
            </Menu.Item>

          </Menu>
          

        </Col>
      </Row>
      
      <Row justify="space-around" wrap="false"
        id="nav-header">
        <Col flex="space-around" className="memu-div" xs={24} sm={24} md={24} lg={24} xl={24}>
          <Menu mode="horizontal"
            id="nav-header-menu"
            onClick={handleClick}
          >
            <Menu.Item key="0">
              <Icon type="home" />
              First
            </Menu.Item>
            <Menu.Item key="video">
              <Icon type="youtube" />
              recommend
            </Menu.Item>
            <Menu.Item key="life">
              <Icon type="smile" />
              Industry
            </Menu.Item>

            <span className="header-txt" id="header-me">标签</span>

          </Menu>
        </Col>
      </Row>
    </div>
  )
}
const Header = () => {
  return (
    <Head>
      <title>Univerity</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <HeaderDes />
    </Head>
  )
}

export default Header