import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import Router from 'next/router';
import Link from 'next/link';
import axios from 'axios';

// import '../static/style/components/header.css'

import { Row, Col, Menu, Icon } from 'antd'
const HeaderDes = () => (
  <div className="header">
    <Row type="flex" justify="center">
      <Col xs={24} sm={24} md={10} lg={10} xl={10}>
        <span className="header-logo">University</span>
        <span className="header-txt">article</span>
      </Col>

      <Col className="memu-div" xs={0} sm={0} md={14} lg={8} xl={6}>
        <Menu mode="horizontal">
          <Menu.Item key="home">
            <Icon type="home" />
            First
          </Menu.Item>
          <Menu.Item key="video">
            <Icon type="youtube" />
            recommend
          </Menu.Item>
          <Menu.Item key="life">
            <Icon type="smile" />
            Industry
          </Menu.Item>
        </Menu>
      </Col>
    </Row>
  </div>
)
const Header = () => {
  return (
    <Head>
      <title>Univerity</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <HeaderDes />
    </Head>
  )
}

export default Header